"""empty message

Revision ID: 120b07d23256
Revises: 5bca9432d5bb
Create Date: 2020-07-29 19:12:31.775885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '120b07d23256'
down_revision = '5bca9432d5bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    op.drop_constraint('it_asset_inventory_location_id_fkey', 'it_asset_inventory', type_='foreignkey')
    op.drop_column('it_asset_inventory', 'location_id')
    op.drop_column('it_assets', 'serial_no')
    op.drop_column('it_assets', 'warranty_expiry')
    op.drop_column('user', 'org_code')
    op.drop_column('user', 'org_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('org_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('org_code', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('it_assets', sa.Column('warranty_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('it_assets', sa.Column('serial_no', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('it_asset_inventory', sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('it_asset_inventory_location_id_fkey', 'it_asset_inventory', 'location', ['location_id'], ['id'])
    op.create_table('location',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('building', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('floor', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('room', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='location_pkey')
    )
    # ### end Alembic commands ###
