"""empty message

Revision ID: 14a09e20c487
Revises: 12e0c74c5477
Create Date: 2020-07-29 22:36:05.342910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a09e20c487'
down_revision = '12e0c74c5477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('badge_no', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    op.drop_constraint('it_asset_inventory_user_id_fkey', 'it_asset_inventory', type_='foreignkey')
    op.create_foreign_key(None, 'it_asset_inventory', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'it_asset_inventory', type_='foreignkey')
    op.create_foreign_key('it_asset_inventory_user_id_fkey', 'it_asset_inventory', 'user', ['user_id'], ['id'])
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('badge_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
