"""empty message

Revision ID: 5bca9432d5bb
Revises: 0bbcc2a06920
Create Date: 2020-07-27 06:23:43.561787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bca9432d5bb'
down_revision = '0bbcc2a06920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('it_assets', sa.Column('warranty_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('it_assets', 'warranty_expiry')
    # ### end Alembic commands ###
