"""empty message

Revision ID: 7f3ad1c19596
Revises: 9eb2e6491e23
Create Date: 2020-07-29 22:38:30.247912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f3ad1c19596'
down_revision = '9eb2e6491e23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('it_asset_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('it_assets_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['it_assets_id'], ['it_assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'it_assets_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('it_asset_inventory')
    # ### end Alembic commands ###
