"""empty message

Revision ID: 84788d434d6e
Revises: 120b07d23256
Create Date: 2020-07-29 19:22:52.201091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84788d434d6e'
down_revision = '120b07d23256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('it_asset_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('it_assets_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['it_assets_id'], ['it_assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'it_assets_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('it_asset_inventory')
    # ### end Alembic commands ###
