"""empty message

Revision ID: 9eb2e6491e23
Revises: 14a09e20c487
Create Date: 2020-07-29 22:38:09.729911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eb2e6491e23'
down_revision = '14a09e20c487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('badge_no', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('it_asset_inventory')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('badge_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('it_asset_inventory',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('it_assets_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['it_assets_id'], ['it_assets.id'], name='it_asset_inventory_it_assets_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='it_asset_inventory_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'it_assets_id', 'user_id', name='it_asset_inventory_pkey')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
