"""empty message

Revision ID: bc477d27c120
Revises: 7f3ad1c19596
Create Date: 2020-07-29 22:39:47.316981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc477d27c120'
down_revision = '7f3ad1c19596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('it_asset_inventory', sa.Column('it_asset_id', sa.Integer(), nullable=False))
    op.drop_constraint('it_asset_inventory_it_assets_id_fkey', 'it_asset_inventory', type_='foreignkey')
    op.create_foreign_key(None, 'it_asset_inventory', 'it_assets', ['it_asset_id'], ['id'])
    op.drop_column('it_asset_inventory', 'it_assets_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('it_asset_inventory', sa.Column('it_assets_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'it_asset_inventory', type_='foreignkey')
    op.create_foreign_key('it_asset_inventory_it_assets_id_fkey', 'it_asset_inventory', 'it_assets', ['it_assets_id'], ['id'])
    op.drop_column('it_asset_inventory', 'it_asset_id')
    # ### end Alembic commands ###
