"""empty message

Revision ID: c23d5cfd036e
Revises: bc477d27c120
Create Date: 2020-07-31 19:04:16.831276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c23d5cfd036e'
down_revision = 'bc477d27c120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('it_assets', 'physical_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('it_assets', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('it_assets', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('it_assets', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('it_assets', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('it_assets', 'physical_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
